build.gradle, src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/general/exception/ErrorResponse.java, src/main/java/run/bemin/api/general/exception/GlobalExceptionHandler.java, src/main/java/run/bemin/api/general/response/ApiResponse.java
<br/>
- String Validation dependency추가
- 공통 응답 생성 (ApiResponse)
- global exception 추가
<br/>
-
<br/>
=> Feat: 공통 응답 & global Exception 생성

build.gradle, src/main/java/run/bemin/api/auth/controller/AuthController.java, src/main/java/run/bemin/api/auth/jwt/JwtUtil.java, src/main/java/run/bemin/api/auth/service/AuthService.java, src/main/java/run/bemin/api/config/WebSecurityConfig.java, src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/security/JwtAuthenticationFilter.java, src/main/java/run/bemin/api/security/JwtAuthorizationFilter.java, src/main/java/run/bemin/api/security/UserDetailsImpl.java, src/main/java/run/bemin/api/security/UserDetailsServiceImpl.java, src/main/java/run/bemin/api/user/controller/UserController.java, src/main/java/run/bemin/api/user/dto/SignupRequestDto.java, src/main/java/run/bemin/api/user/dto/SignupResponseDto.java, src/main/java/run/bemin/api/user/entity/User.java, src/main/java/run/bemin/api/user/entity/UserRoleEnum.java, src/main/java/run/bemin/api/user/exception/UserException.java, src/main/java/run/bemin/api/user/exception/UserExceptionHandler.java, src/main/java/run/bemin/api/user/repository/UserRepository.java
<br/>
- Spring Security 설정 적용 (WebSecurityConfig 추가)
- JWT 인증을 위한 secret key 설정 (application.yml)
- build.gradle에 Security 및 JWT 관련 의존성 추가
- 회원가입 기능 구현 (회원 정보 저장, 비밀번호 암호화)
- ErrorCode에 회원가입 관련 오류 코드 추가 (S001, S002)
- user 도메인에 한정된 예외 처리 (UserException 및 UserExceptionHandler 추가)
<br/>
-
<br/>
=> Feat: Security 설정 및 JWT 기반 회원가입 기능 구현

src/main/java/run/bemin/api/auth/service/AuthService.java, src/main/java/run/bemin/api/config/WebSecurityConfig.java, src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/user/controller/UserController.java, src/main/java/run/bemin/api/user/dto/EmailCheckResponseDto.java, src/main/java/run/bemin/api/user/repository/UserRepository.java, src/main/java/run/bemin/api/user/service/UserService.java
<br/>
- 회원가입 시 이메일 중복 여부를 확인하는 API 추가
- 이메일 형식 검증 로직 추가
- ErrorCode에 이메일 관련 오류 코드 추가 (S003, S004)
- WebSecurityConfig에 `/api/users/email/**` 접근 허용 (`permitAll()`) 추가
- `EmailCheckResponseDto` 추가
<br/>
-
<br/>
=> Feat: 이메일 중복 확인 기능 구현 및 보안 설정 적용

src/main/java/run/bemin/api/config/WebSecurityConfig.java, src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/general/exception/GlobalExceptionHandler.java, src/main/java/run/bemin/api/user/controller/UserController.java, src/main/java/run/bemin/api/user/dto/NicknameCheckResponseDto.java, src/main/java/run/bemin/api/user/repository/UserRepository.java, src/main/java/run/bemin/api/user/service/UserService.java
<br/>
- 닉네임 중복 확인 기능 구현
- EmailCheckResponseDto 수정
- 이메일 중복 체크 시 null 값 검증을 Controller에서 처리하도록 수정
- GlobalExceptionHandler에서 @NotBlank 검증 시 특정 메시지에 맞게 오류 처리 추가
- WebSecurityConfig에 `/api/users/nickname/**` 접근 허용 (`permitAll()`) 추가
<br/>
-
<br/>
=> Feat: 닉네임 중복 확인 기능 구현

src/main/java/run/bemin/BeminApplication.java, src/main/java/run/bemin/api/general/auditing/AuditableEntity.java, src/main/java/run/bemin/api/general/auditing/AuditorAwareImpl.java, src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/product/entity/Product.java, src/main/java/run/bemin/api/product/entity/ProductEntityService.java, src/main/java/run/bemin/api/product/repository/ProductRepository.java
<br/>
- product entity 추가
- Auditing entity 추가
<br/>
-
<br/>
=> Feat : Product 및 Auditing 엔티티 추가

src/main/java/run/bemin/api/config/WebSecurityConfig.java
- WebSecurityConfig 필터 로직 수정
<br/>
- WebSecurityConfig 필터 로직 수정
<br/>
-
<br/>
=> Fix: WebSecurityConfig 필터 로직 수정

src/main/java/run/bemin/api/category/controller/AdminCategoryController.java, src/main/java/run/bemin/api/category/dto/request/CreateCategoryRequestDto.java, src/main/java/run/bemin/api/category/service/CategoryService.java
=> 카테고리 등록 API 권한 검사하기

src/main/java/run/bemin/api/auth/jwt/JwtUtil.java, src/main/java/run/bemin/api/product/entity/Product.java, src/test/java/run/bemin/security/JwtUtilTokenTest.java
<br/>
- JWT 토큰의 페이로드에서 사용자 이메일(Subject) 정보를 추출하는 메서드 추가
- 관련 테스트 케이스 작성 및 검증 완료
<br/>
-
<br/>
=> Feat: 토큰에서 사용자 이메일 추출 기능 구현

src/main/java/run/bemin/api/auth/jwt/JwtUtil.java, src/main/java/run/bemin/api/user/exception/handler/UserExceptionHandler.java
- 전역 예외 핸들러보다 우선순위를 높이기 위해 설정했던 @Order(Ordered.HIGHEST_PRECEDENCE) 제거
- JwtUtilTokenTest 대응을 위해 접근 제어자를 public으로 변경
<br/>
- 전역 예외 핸들러보다 우선순위를 높이기 위해 설정했던 @Order(Ordered.HIGHEST_PRECEDENCE) 제거
- JwtUtilTokenTest 대응을 위해 접근 제어자를 public으로 변경
<br/>
-
<br/>
=> Refactor: @Order 어노테이션 제거 및 접근 제어자 public 변경

src/main/java/run/bemin/api/comment/entity/Comment.java, src/main/java/run/bemin/api/comment/repository/CommentRepository.java
=> Feat: Comment 도메인 생성

src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/user/controller/UserController.java, src/main/java/run/bemin/api/user/dto/UserResponseDto.java, src/main/java/run/bemin/api/user/dto/UserUpdateRequestDto.java, src/main/java/run/bemin/api/user/entity/User.java, src/main/java/run/bemin/api/user/exception/UserDuplicateNicknameException.java, src/main/java/run/bemin/api/user/exception/UserNoFieldUpdatedException.java, src/main/java/run/bemin/api/user/exception/UserNotFoundException.java, src/main/java/run/bemin/api/user/exception/handler/UserExceptionHandler.java, src/main/java/run/bemin/api/user/repository/UserRepository.java, src/main/java/run/bemin/api/user/service/UserService.java
<br/>
- ErrorCode 추가 (USER_NOT_FOUND)
- UserNotFoundException 예외처리 생성 및 적용
- 비밀번호, 닉네임, 핸드폰, 주소 중 하나 이상 입력 시 해당 필드만 업데이트
- 입력된 필드가 없으면 예외 처리
<br/>
-
<br/>
=> Feat: 특정 사용자 상세 정보 조회 기능 구현 및 사용자 정보 수정 기능 구현

build.gradle, src/main/java/run/bemin/api/comment/config/ChatGPTConfig.java, src/main/java/run/bemin/api/comment/controller/CommentController.java, src/main/java/run/bemin/api/comment/dto/CommentDto.java, src/main/java/run/bemin/api/comment/dto/CommentListDto.java, src/main/java/run/bemin/api/comment/dto/CommentRequestDto.java, src/main/java/run/bemin/api/comment/dto/CommentResponseDto.java, src/main/java/run/bemin/api/comment/dto/GPTRequest.java, src/main/java/run/bemin/api/comment/dto/GPTResponse.java, src/main/java/run/bemin/api/comment/dto/Message.java, src/main/java/run/bemin/api/comment/repository/CommentRepository.java, src/main/java/run/bemin/api/comment/service/ChatGPTService.java, src/main/java/run/bemin/api/comment/service/CommentService.java, src/main/java/run/bemin/api/product/controller/ProductController.java, src/main/java/run/bemin/api/product/entity/Product.java, src/main/java/run/bemin/api/product/service/ProductService.java
<br/>
- OpenAi 연동
- Comment Service 생성
- comment 생성 (openAI)
- comment 저장
- comment 조회 (생성일 기준 최신순으로 5개 가져옵니다.)
- product의 comment 변경 
<br/>
- OpenAI 관련 API 요청시 결제해둔 토큰에서 차감됩니다. 충분히 충천해놓긴 했지만, 과도한 요청은 자제해주세요 🙏
<br/>
=> Feat: Comment 도메인 Controller & Service 생성

src/main/java/run/bemin/api/category/dto/request/CreateCategoryRequestDto.java, src/main/java/run/bemin/api/category/repository/CategoryRepository.java, src/main/java/run/bemin/api/store/dto/StoreDto.java, src/main/java/run/bemin/api/store/dto/StoreValidationMessages.java, src/main/java/run/bemin/api/store/dto/request/CreateStoreRequestDto.java, src/main/java/run/bemin/api/store/entity/Store.java, src/main/java/run/bemin/api/store/entity/StoreAddress.java, src/main/java/run/bemin/api/store/exception/CategoryCountExceededException.java, src/main/java/run/bemin/api/store/exception/handler/StoreExceptionHandler.java, src/main/java/run/bemin/api/store/service/StoreService.java
가게 조회 연관 관계 매핑하기
<br/>
-
<br/>
-
<br/>
=> Feat: #32 가게 조회 연관 관계 매핑하기

src/main/java/run/bemin/api/general/auditing/AuditableEntity.java
필드 update 수정하기
<br/>
-
<br/>
-
<br/>
=> Refactor: #32 필드 update 수정하기

src/main/java/run/bemin/api/general/auditing/AuditorAwareImpl.java, src/main/java/run/bemin/api/user/entity/User.java
회원 가입 시점에는 스프링 시큐리티 세션 안에 정보가 없습니다..!
따라서 이 경우를 해결하고자 다음과 같이 Optional로 체크하고 null을 반환할 수 있도록 수정합니다..!
<br/>
-
<br/>
- #51 
<br/>
=> Refactor: #51 회원가입을 고려한 Audit 수정하기

src/main/java/run/bemin/api/payment/controller/PaymentController.java, src/main/java/run/bemin/api/payment/domain/PaymentStatus.java, src/main/java/run/bemin/api/payment/dto/CreatePaymentDto.java, src/main/java/run/bemin/api/payment/dto/PaymentDto.java, src/main/java/run/bemin/api/payment/entity/Payment.java, src/main/java/run/bemin/api/payment/service/PaymentService.java
<br/>
- Payment 도메인과 Order 도메인 연결
- Payment 와 general/auditing 까지 연결 완료
- Error Code 작성은 Payment 수정 및 삭제 API 구현 때, 같이 업로드 하겠습니다.
<br/>
-
<br/>
=> Fix: Payment 도메인과 Order 도메인, auditing 까지 연결하여 결제 생성 API 구현 완료

src/main/java/run/bemin/api/category/controller/AdminCategoryController.java, src/main/java/run/bemin/api/category/controller/CategoryController.java
각 카테고리 데이터 API는 적절한 권한을 부여 받는다.
<br/>
-
<br/>
- #31 
<br/>
=> Refactor: #31 카테고리 API 권한 적용하기

src/main/java/run/bemin/api/category/dto/CategoryValidationMessages.java, src/main/java/run/bemin/api/category/dto/request/SoftDeleteCategoryRequestDto.java, src/main/java/run/bemin/api/category/dto/request/UpdateCategoryRequestDto.java, src/main/java/run/bemin/api/category/service/CategoryService.java
회원 권한에 따른 API 접근 및 회원 정보를 더이상 직접 입력하지 않고 UserDetails 에서 가져오도록 수정했습니다.
<br/>
-
<br/>
- This closes #31
<br/>
=> 카테고리 API 수정하기

src/main/java/run/bemin/api/review/controller/ReviewController.java, src/main/java/run/bemin/api/review/domain/ReviewRating.java, src/main/java/run/bemin/api/review/dto/ReviewCreateRequestDto.java, src/main/java/run/bemin/api/review/dto/ReviewCreateResponseDto.java, src/main/java/run/bemin/api/review/dto/ReviewUpdateRequestDto.java, src/main/java/run/bemin/api/review/dto/ReviewUpdateResponseDto.java, src/main/java/run/bemin/api/review/entity/Review.java, src/main/java/run/bemin/api/review/exception/ReviewException.java, src/main/java/run/bemin/api/review/repository/ReviewRepository.java, src/main/java/run/bemin/api/review/service/ReviewService.java
<br/>
- 리뷰 생성하기
- 리뷰 수정하기
- entity, service, dto, controller 부분이 변경되었습니다.
<br/>
- 제가 작업하기 전부터 error code 부분이 이상한데 이 부분 한 번 확인해주세요..!!
<br/>
=> Feat: 리뷰 수정하기 기능 구현, Fix: 리뷰 생성하기 기능 수정

src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/review/controller/ReviewController.java, src/main/java/run/bemin/api/review/dto/ReviewDeleteResponseDto.java, src/main/java/run/bemin/api/review/entity/Review.java, src/main/java/run/bemin/api/review/service/ReviewService.java
<br/>
- 리뷰 삭제하기 기능 추가하였습니다.
- Error Code 부분 기존 코드 그래도 살려두었습니다. 혹시 모르니 각자 한 번씩 체크해주세요!
<br/>
-
<br/>
=> Feat: 리뷰 삭제하기, Fix: Error Code 기존 부분 최대한 살려서 수정

src/main/java/run/bemin/api/product/controller/ProductController.java
=> Fix: product controller 요청 URL 수정

src/main/java/run/bemin/api/general/exception/ErrorCode.java
STORE_ALREADY_DELETE 구현하기
<br/>
-
<br/>
- #64 
<br/>
=> Fix: #64 가게 예외 응답 구현하기

src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/payment/controller/PaymentController.java, src/main/java/run/bemin/api/payment/dto/PaymentStatusResponseDto.java, src/main/java/run/bemin/api/payment/repository/PaymentRepository.java, src/main/java/run/bemin/api/payment/service/PaymentService.java, src/main/java/run/bemin/api/review/controller/ReviewController.java, src/main/java/run/bemin/api/review/domain/ReviewStatus.java, src/main/java/run/bemin/api/review/dto/ReviewCreateRequestDto.java, src/main/java/run/bemin/api/review/dto/ReviewCreateResponseDto.java, src/main/java/run/bemin/api/review/entity/Review.java, src/main/java/run/bemin/api/review/repository/ReviewRepository.java, src/main/java/run/bemin/api/review/service/ReviewService.java
<br/>
- controller, dto, repository, service 수정
- 사용자가 결제한 주문 내역의 결제 상태 조회
<br/>
-
<br/>
=> Feat: 결제 상태 조회 기능 구현

src/main/java/run/bemin/api/auth/controller/AuthController.java, src/main/java/run/bemin/api/auth/dto/SigninResponseDto.java, src/main/java/run/bemin/api/auth/dto/SignoutResponseDto.java, src/main/java/run/bemin/api/auth/service/AuthService.java
<br/>
- 추후 확장성(블랙리스트, Redis 활용 등)을 고려하여 로그아웃을 구현할 수 있도록 했습니다.
- 현재는 JWT 기반 로그아웃은 클라이언트가 토큰을 제거하면 처리되므로, 서버 측에서는 단순히 성공 메시지만 반환하도록 했습니다.
- 클라이언트가 토큰을 제거하여 로그아웃을 완료하도록 처리함.
- 로그인시 응답에 로그인한 유저의 role 필드 추가 (SigninResponseDto)
<br/>
-
<br/>
=> Feat: 로그아웃 기능 구현 (JWT 기반)

src/main/java/run/bemin/api/user/service/UserService.java
<br/>
- 페이지 요청 시 sortOrder 파라미터에 따라 생성일(createdAt) 기준 오름차순/내림차순 정렬 처리
- 기본값은 내림차순("desc")이며, "asc" 입력 시 오름차순 정렬
-
<br/>
=> Refactor: 전체 회원 조회 시 생성일 기준 정렬 기능 추가

src/main/java/run/bemin/api/store/controller/AdminStoreController.java, src/main/java/run/bemin/api/store/dto/StoreDto.java, src/main/java/run/bemin/api/store/dto/request/StoreActivationStatusDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateAddressInStoreRequestDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateCategoriesInStoreRequestDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateStoreActivationRequestDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateStoreOwnerRequestDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateStorePhoneRequestDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateStoresActivationStatusRequestDto.java, src/main/java/run/bemin/api/store/dto/response/UpdateCategoriesInStoreResponseDto.java, src/main/java/run/bemin/api/store/entity/Store.java, src/main/java/run/bemin/api/store/service/StoreService.java
=> 가게 수정 API 추가 구현하기

build.gradle, src/main/java/run/bemin/api/store/controller/StoreController.java, src/main/java/run/bemin/api/store/dto/StoreSimpleDto.java, src/main/java/run/bemin/api/store/repository/StoreRepository.java, src/main/java/run/bemin/api/store/repository/StoreRepositoryCustom.java, src/main/java/run/bemin/api/store/repository/StoreRepositoryImpl.java, src/main/java/run/bemin/api/store/service/StoreService.java, src/main/java/run/bemin/api/user/entity/User.java
QueryDSL을 사용하기 위해 엔티티 매니저를 기반으로 JPAQueryFactory 인스턴스를 생성합니다.
BooleanBuilder 사용:
동적 조건을 구성하기 위해 BooleanBuilder를 생성합니다.
카테고리 조건:
만약 categoryName이 null이 아니고 비어있지 않다면,
category.name.eq(categoryName) 조건을 추가하여 카테고리 이름과 정확히 일치하는 결과만 필터링합니다.
지점 이름 조건:
만약 storeName이 null이 아니고 비어있지 않다면,
store.name.containsIgnoreCase(storeName) 조건을 추가하여 지점 이름에 해당 키워드가 포함된 결과를 필터링합니다.
기본 쿼리 생성:
queryFactory.selectFrom(store)를 통해 Store 엔티티를 대상으로 쿼리를 생성합니다.
distinct 사용:
여러 조인으로 인해 중복된 Store 객체가 발생할 수 있으므로 distinct()를 사용해 중복을 제거합니다.
조인:
store.storeCategories와 storeCategory를 좌측 조인(left join)
이어서 storeCategory.category와 category를 좌측 조인하여, 연관된 카테고리 정보를 가져옵니다.
동적 조건 적용:
앞서 구성한 BooleanBuilder의 조건(builder)을 where(builder)를 통해 적용합니다.
```
JPAQuery<Store> query = queryFactory.selectFrom(store)
.distinct() …
```
=> 3. QueryDSL 구현하기

src/main/java/run/bemin/api/general/exception/ErrorCode.java, src/main/java/run/bemin/api/order/control/MasterOrderController.java, src/main/java/run/bemin/api/order/control/OrderController.java, src/main/java/run/bemin/api/order/control/OwnerOrderController.java, src/main/java/run/bemin/api/order/dto/OrderResponseCode.java, src/main/java/run/bemin/api/order/dto/request/DeleteOrderRequest.java, src/main/java/run/bemin/api/order/entity/OrderDomainService.java, src/main/java/run/bemin/api/order/exception/OrderCantCancelled.java, src/main/java/run/bemin/api/order/exception/handler/OrderExceptionHandler.java, src/main/java/run/bemin/api/order/repo/OrderRepository.java, src/main/java/run/bemin/api/order/service/OrderMasterService.java, src/main/java/run/bemin/api/order/service/OrderOwnerService.java, src/main/java/run/bemin/api/order/service/OrderService.java
<br/>
- USER_ROLE에 따라서 사용하는 컨트롤러, 서비스 분리
- OWNER는 소유한 가게를 기준으로, Order서비스를 이용할 수 있게 Store와 연동
- 날짜로 order를 서치하는 기능 추가
- Master, Manager가 할 수 있는 softDelete기능 추가
<br/>
-
<br/>
=> Feature: USER_ROLE에 따른 Order 기능 분리

src/main/java/run/bemin/api/user/controller/UserController.java, src/main/java/run/bemin/api/user/entity/User.java, src/main/java/run/bemin/api/user/entity/UserAddress.java, src/main/java/run/bemin/api/user/service/UserService.java
<br/>
- User.softDelete() 호출 시 해당 User와 연관된 모든 UserAddress도 soft delete 처리
- User 엔티티에 is_deleted 필드(@Builder.Default 적용) 추가
- UserAddress 엔티티에 is_deleted 필드, deleted_at, deleted_by 및 Auditing 연결 적용
- softDelete() 메서드 수정: 각 엔티티에서 isDeleted를 true로 설정하고 deletedAt, deletedBy 기록
<br/>
-
<br/>
=> Feat: User와 UserAddress 소프트 삭제 및 Auditing 적용

src/main/java/run/bemin/api/store/controller/AdminStoreController.java
이메일로 가게 목록 조회 API 수정을 다음과 같이 진행합니다.
권한 검사 수정
스프링 시큐리티 세션 정보로부터(로그인한 사용자로부터) 가게 조회
<br/>
-
<br/>
-
<br/>
=> 이메일로 단 건 가게 목록 조회 API 수정하기

src/main/java/run/bemin/api/review/controller/ReviewController.java, src/main/java/run/bemin/api/review/dto/PageInfoDto.java, src/main/java/run/bemin/api/review/dto/PagedReviewResponseDto.java, src/main/java/run/bemin/api/review/dto/ReviewResponseDto.java, src/main/java/run/bemin/api/review/entity/Review.java, src/main/java/run/bemin/api/review/repository/ReviewRepository.java, src/main/java/run/bemin/api/review/service/ReviewService.java, src/main/java/run/bemin/api/user/entity/User.java
<br/>
- 특정 가게에 대한 리뷰 페이징 처리, 생성순/수정순 정렬
<br/>
-
<br/>
=> Feat: 리뷰 페이징 처리, 생성순/수정순 정렬   

src/main/java/run/bemin/api/user/controller/UserController.java, src/main/java/run/bemin/api/user/dto/UserAddressResponseDto.java, src/main/java/run/bemin/api/user/dto/UserResponseDto.java, src/main/java/run/bemin/api/user/repository/UserAddressRepository.java, src/main/java/run/bemin/api/user/repository/UserRepository.java, src/main/java/run/bemin/api/user/service/UserAddressService.java, src/main/java/run/bemin/api/user/service/UserService.java
<br/>
[소프트 삭제, Auditing, 대표 주소 변경, 페이징/정렬 개선]
- User와 UserAddress 소프트 삭제 및 Auditing 적용
- 대표 주소 변경 기능 추가
- getAddresses 반환 타입을 List에서 Page로 변경 및 정렬 로직 업데이트
- 페이징 처리된 Page<UserAddressResponseDto> 반환으로 수정
- 대표 주소(isRepresentative가 true인)가 항상 최상단에 오고, 나머지 주소들은 생성일(createdAt) 기준 오름차순으로 정렬되도록 구현
- 전체 회원 조회 API 개선
- 추가 파라미터 isDeleted를 통해 회원 탈퇴 여부에 따른 필터링이 가능하도록 수정 (값이 없으면 전체 조회).
- isDeleted 필터 및 회원 탈퇴 여부 표시 추가
<br/>
-
<br/>
=> Feat: 회원 및 주소 관리 API 개선

src/main/java/run/bemin/api/store/entity/Store.java
updateRating 메서드 추가하기
<br/>
- Store.java 파일 수정하기
- updateRating 메서드 추가
<br/>
-
<br/>
=> Fix: Store.java 수정

src/main/java/run/bemin/api/store/dto/StoreDto.java, src/main/java/run/bemin/api/store/dto/request/UpdateAllStoreRequestDto.java, src/main/java/run/bemin/api/store/repository/StoreRepositoryImpl.java
=> 🎉🎉🎉[#100돌파] API 명세서 최신화에 따른 수정 사항 반영하기 🎉🎉🎉

src/main/java/run/bemin/api/product/repository/ProductRepository.java
=> Fix: @Param 추가
